# 🐍 Day 23 — NumPy Array Creation Functions

## Day 21 mein humne NumPy arrays ki foundation banayi aur Day 22 mein unke saath operations kiye. 🔥

## Aaj hum seekhenge ki NumPy mein different ways se arrays kaise create karte hain.

## Ye functions Data Analysis mein kaafi useful honge, especially jab humein predefined values, ranges, evenly spaced values ya random data create karna ho.

# 🎯 Day 23 Goals

## Aaj ye concepts karenge:

###np.zeros()
###np.ones()
###np.full()
###np.arange()
###np.linspace()
###np.eye()
###np.random.rand()
###np.random.randint()
###np.arange() vs np.linspace()
###Different shapes ke arrays create karna
###Practical examples
###Practice questions

# 1. np.zeros()
### np.zeros() ek aisa NumPy array create karta hai jisme saare elements 0 hote hain.

In [1]:
import numpy as np

arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


## 🧠 Important

###Default mein zeros ka data type generally float hota hai.

# Agar humein integers chahiye:

In [2]:
arr = np.zeros(5, dtype=int)

print(arr)

[0 0 0 0 0]


# 2D Array using np.zeros()

##Hum tuple ke through shape de sakte hain:

In [3]:
arr = np.zeros((2, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


# 2. np.ones()
##np.ones() ek array create karta hai jisme saare elements 1 hote hain.

In [4]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


# Integer Version:

In [5]:
arr = np.ones(5, dtype=int)

print(arr)

[1 1 1 1 1]


# 2D np.ones()

In [6]:
arr = np.ones((3, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 3. np.full()

##np.full() ka use tab karte hain jab humein har position par same value chahiye.

In [7]:
arr = np.full(5, 10)

print(arr)

[10 10 10 10 10]


# 2D Example:

In [8]:
arr = np.full((2, 3), 7)

print(arr)

[[7 7 7]
 [7 7 7]]


#4. np.arange()

##Ye function range ke according values generate karta hai.

##Python ke range() ki tarah concept hai.

In [9]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


#🧠 Important

##stop value include nahi hoti.

# Steps ke Sath:

In [10]:
arr = np.arange(0, 11, 2)

print(arr)

[ 0  2  4  6  8 10]


# Negative Steps:

In [11]:
arr = np.arange(10, 0, -2)

print(arr)

[10  8  6  4  2]


#5. np.linspace()

##np.linspace() ka use evenly spaced numbers generate karne ke liye hota hai.

In [12]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


#🧠 Important Difference

##np.arange() mein hum generally step size specify karte hain.

####np.arange(0, 10, 2)

##While np.linspace() mein hum kitni values chahiye specify karte hain.

####np.linspace(0, 10, 6)
#6. np.arange() vs np.linspace()

##Ye difference important hai. 🔥

#arange()
####arr = np.arange(0, 11, 2)

####print(arr)

#Output:

[ 0  2  4  6  8 10]

# Humne bola:

###0 se start karo, 11 se pehle tak jao, har baar 2 ka jump karo.

#linspace()

####arr = np.linspace(0, 10, 6)

####print(arr)

##Output:

[ 0.  2.  4.  6.  8. 10.]

##Humne bola:

###0 se 10 tak 6 values do.

#🧠 Mind Template
##arange  → "step kitna ho?"
##linspace → "values kitni chahiye?"

###Ye simple trick yaad rakhna.

#7. np.eye()

##np.eye() ka use identity matrix create karne ke liye hota hai.

In [13]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr = np.eye(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#8. np.random.rand()

##Ab random arrays.

##np.random.rand() random decimal values generate karta hai between:

##-> 0 and 1

In [15]:
arr = np.random.rand(5)

print(arr)

[0.11417437 0.28189927 0.00767248 0.9030069  0.42330135]


# 2D Random Array

In [16]:
arr = np.random.rand(2, 3)

print(arr)

[[0.00738656 0.81615656 0.45835165]
 [0.13699106 0.62294699 0.92440962]]


#9. np.random.randint()

##Agar humein random integers generate karne hain, toh np.random.randint() use kar sakte hain.

In [17]:
arr = np.random.randint(1, 10, 5)

print(arr)

[2 1 5 1 3]


# 2D Random Integer

In [18]:
arr = np.random.randint(1, 100, (3, 4))

print(arr)

[[39 46  1 20]
 [ 8  2 86 27]
 [64 56  9 36]]


#🔥 Practical Example 1 — Student Marks

##Suppose humein 5 students ke marks temporarily store karne hain:

In [19]:
marks = np.random.randint(0, 101, 5)

print(marks)

[71 44 44 60  6]


## Ab Day-22 ke functions ka use krke:

In [20]:
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Total: 225
Average: 45.0
Highest: 71
Lowest: 6


#🔥 Practical Example 2 — Temperature Data

##Suppose humein 7 days ka sample temperature data create karna hai:

In [21]:
temperature = np.random.randint(20, 41, 7)

print(temperature)

[40 28 25 21 38 35 22]


In [22]:
print("Average Temperature:", np.mean(temperature))
print("Maximum Temperature:", np.max(temperature))
print("Minimum Temperature:", np.min(temperature))

Average Temperature: 29.857142857142858
Maximum Temperature: 40
Minimum Temperature: 21


#📝 Day 23 Practice


##Q1 — Zeros

###5 elements ka NumPy array banao jisme saare elements 0 hon.

###Then ek 3 × 4 array banao jisme saare elements 0 hon.

In [23]:
arr=np.zeros(5)
print(arr)
arr1=np.zeros((3,4))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#Q2 — Ones

##10 elements ka array banao jisme saare elements 1 hon.

##Then ek 2 × 3 array banao jisme saare elements 1 hon.

In [24]:
arr=np.ones(10)
print(arr)
arr1=np.ones((2,3))
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


#Q3 — Full

##Ek 3 × 3 array banao jisme har element 7 ho.

In [25]:
arr=np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


#Q4 — Arange

##10 se 50 tak ke even numbers generate karo using np.arange().

In [27]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#Q5 — Linspace

##0 se 100 ke beech 11 evenly spaced values generate karo.

In [28]:
arr=np.linspace(0,100,11)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


#Q6 — Identity Matrix

##Ek 5 × 5 identity matrix create karo using np.eye().

In [29]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#Q7 — Random

##1 se 100 ke beech 10 random integers generate karo.

In [30]:
arr=np.random.randint(1,100,10)
print(arr)

[23  8 45 56 15 56 61 72 41 79]


#Q8 — Random 2D Array

##10 se 50 ke beech random integers ka 3 × 4 array create karo.

In [31]:
arr=np.random.randint(10,50,(3,4))
print(arr)

[[31 30 42 39]
 [18 23 30 28]
 [17 36 12 26]]
