# 🐍 Day 24 — NumPy Indexing, Slicing & Reshaping

###Aaj hum NumPy arrays ke saath indexing, slicing aur reshaping deeply samjhenge. Ye concepts bahut important hain because Data Analysis aur ML mein hume arrays ke specific elements/data portions ko access aur transform karna hota hai.

#🎯 Day 24 Goals

##Aaj hum seekhenge:

###NumPy Indexing
###1D Array Indexing
###2D Array Indexing
###Negative Indexing
###NumPy Slicing
###1D Slicing
###2D Slicing
###Row & Column Selection
###reshape()
###flatten() vs ravel()
###Practical examples
###Practice Questions

# 1.NumPy Indexing

##Indexing ka matlab hai array ke kisi particular element ko access karna.

##Python ki tarah NumPy mein bhi indexing 0 se start hoti hai.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


# 2.Negative Indexing

##Negative indexing array ke end se elements access karne ke liye use hoti hai.

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10


# 3.2D Array Indexing

##2D array mein hume row aur column dono specify karne hote hain.

In [3]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0, 0])
print(arr[1, 2])
print(arr[2, 1])

10
60
80


# 4.Accessing Complete Rows

##2D array mein complete row bhi access kar sakte hain.

In [4]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0])
print(arr[1])
print(arr[2])

[10 20 30]
[40 50 60]
[70 80 90]


# 5.Accessing Complete Columns

##Complete column access karne ke liye:

In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[:, 0])
print(arr[:, 1])
print(arr[:, 2])

[10 40 70]
[20 50 80]
[30 60 90]


# 6.NumPy Slicing

##Slicing ka matlab hai array ka ek portion extract karna.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


###⚠️ stop index included nahi hota.

# 7. Slicing with Step

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[0:6:2])

[10 30 50]


# 8. Slicing from Beginning

##Start index omit kar sakte hain.

In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[:3])

[10 20 30]


# 9. Slicing Till End

###Stop index omit kar sakte hain.

In [9]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2:])

[30 40 50]


# 10. Reverse an Array

###Negative step use karke array reverse kar sakte hain.

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[::-1])

[50 40 30 20 10]


# 11. 2D Array Slicing

##2D slicing thoda important hai.

In [11]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arr[0:2, 1:3])

[[2 3]
 [6 7]]


# 12. Select First Two Rows

In [12]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[:2])

[[1 2 3]
 [4 5 6]]


# 13. Select First Two Columns

In [13]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


# 14. Reshaping NumPy Arrays

###reshape() ka use array ka shape change karne ke liye hota hai.

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)
print(new_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#🧠 Important Rule

##reshape() karte waqt total number of elements same rehna chahiye.

# 15. More Reshape Examples

In [15]:
arr = np.arange(1, 13)

print(arr)

arr2 = arr.reshape(3, 4)

print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 16. Reshape into 3D

##NumPy sirf 1D → 2D nahi karta. Higher dimensions bhi possible hain.

In [16]:
arr = np.arange(1, 13)

new_arr = arr.reshape(2, 2, 3)

print(new_arr)
print(new_arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# 17. -1 in reshape()

###NumPy automatically ek dimension calculate kar sakta hai using -1.

In [17]:
arr = np.arange(1, 13)

new_arr = arr.reshape(3, -1)

print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#🧠 Important Point

###-1 ka matlab:

###"Ye dimension NumPy khud calculate kar le."

# 18. flatten()

###flatten() multidimensional array ko 1D array mein convert karta hai.

In [18]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.flatten()

print(flat)
print(flat.shape)

[1 2 3 4 5 6]
(6,)


# 19. ravel()

###ravel() bhi array ko 1D mein convert karta hai.

In [20]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.ravel()

print(flat)

[1 2 3 4 5 6]


#🧠 Beginner Level Difference

#Abhi ke liye simple rule yaad rakho:

##flatten() → 1D copy
##ravel()   → 1D view possible

###ravel() generally memory efficient ho sakta hai because ye possible hone par original data ka view return karta hai.

# 20. Practical Example — Student Marks

###Suppose 3 students ke 4 subjects ke marks hain.

In [21]:
marks = np.array([
    [85, 90, 78, 92],
    [70, 75, 80, 72],
    [95, 88, 91, 94]
])

print("All Marks:")
print(marks)

print("\nFirst Student:")
print(marks[0])

print("\nMaths Marks:")
print(marks[:, 0])

print("\nFirst Two Students:")
print(marks[:2])

All Marks:
[[85 90 78 92]
 [70 75 80 72]
 [95 88 91 94]]

First Student:
[85 90 78 92]

Maths Marks:
[85 70 95]

First Two Students:
[[85 90 78 92]
 [70 75 80 72]]


# 🧠 Important

###Is type ki indexing/slicing Data Analysis mein frequently use hoti hai.

# Practical Example — Dataset Portion

##Imagine karo:


data =
np.array([
    
    [101, 20, 50000],
    
    [102, 25, 60000],
    
    [103, 30, 75000],
    
    [104, 28, 65000]])

# Columns:

### ID | Age | Salary

## Age column:

print(data[:, 1])

###Output:
[20 25 30 28]

##Salary column:

print(data[:, 2])
###Output
[50000 60000 75000 65000]

##First 2 rows:

print(data[:2])
###Output:
[
[  101    20 50000]

[  102    25 60000]]

In [23]:
data = np.array([
    [101, 20, 50000],
    [102, 25, 60000],
    [103, 30, 75000],
    [104, 28, 65000]])

In [24]:
# Age Column:
print(data[:, 1])

[20 25 30 28]


In [25]:
#Salary column:

print(data[:, 2])

[50000 60000 75000 65000]


In [26]:
#First 2 rows:

print(data[:2])

[[  101    20 50000]
 [  102    25 60000]]


# 📝 Day 24 Practice
##Q1 — Basic Indexing

###Create:

arr = np.array([10, 20, 30, 40, 50, 60])

###Print:

####first element
####third element
####last element
####second-last element

In [27]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[-2])

10
30
60
50


# Q2 — 2D Indexing

###Create:

[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]

###Find:

####50
####90
####20

###using indexing.

In [29]:
arr=np.array([10,20,30,40,50,60,70,80,90])
arr1=arr.reshape(3,3)
print(arr1)
print(arr1[1,1])
print(arr1[2,2])
print(arr1[0,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
90
20


#Q3 — Row Selection

##Given:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

##Print:

###first row
###third row
###last row

In [31]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(arr[0])
print(arr[2])
print(arr[-1])

[1 2 3]
[7 8 9]
[10 11 12]


#Q4 — Column Selection

##Using the same array, print:

###first column
###second column
###third column

In [36]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(arr[:,0])
print(arr[:,1])
print(arr[:,2])

[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]


#Q5 — 1D Slicing

##Given:

arr = np.arange(1, 21)

##Extract:

###first 5 elements
###elements from index 5 to 10
###last 5 elements
###every second element

In [38]:
arr = np.arange(1, 21)
print(arr)
print(arr[:5])
print(arr[5:11])
print(arr[-5:])
print(arr[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]
[ 6  7  8  9 10 11]
[16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


#Q6 — Reverse

##Given:

###arr = np.arange(1, 11)

##Reverse the array using slicing.

In [42]:
arr = np.arange(1, 11)
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


#Q7 — 2D Slicing

##Given:

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

##Extract:

[ [6, 7],
  [10, 11] ]

##using slicing.

In [43]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(arr[1:3, 1:3])

[[ 6  7]
 [10 11]]


#Q8 — Reshape

##Create:

arr = np.arange(1, 13)

##Convert it into:

###3 × 4

##and then:

###4 × 3

In [44]:
arr = np.arange(1, 13)
arr_3x4 = arr.reshape(3, 4)
print(arr_3x4)
arr_4x3 = arr.reshape(4, 3)
print(arr_4x3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
