#🐍 Day 25 — NumPy Boolean Indexing, Filtering & Conditional Selection

##Bhai, aaj NumPy ka bahut important practical concept start karenge: Boolean Indexing / Filtering.

##Ye concept especially important hai because real datasets mein hume aksar condition ke basis par data nikalna hota hai.

#Example:

###“Sirf woh students nikalo jinke marks 80 se zyada hain.”

###NumPy mein ye kaafi easily ho sakta hai.

#🎯 Day 25 Goals

##Aaj hum seekhenge:

####Boolean conditions in NumPy
####Comparison operators
####Boolean arrays
####Boolean indexing
####Filtering values
####Multiple conditions
####& — AND
####| — OR
####~ — NOT
####np.where()
####Practical examples
####Practice Questions

# 1. Boolean Conditions in NumPy

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr > 30)

[False False False  True  True]


#🧠 Important Point

###NumPy comparison operation ka result ek Boolean array hota hai.

# 2. Different Comparison Operators

###NumPy mein normal comparison operators use kar sakte hain:

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 30)
print(arr < 30)
print(arr >= 30)
print(arr <= 30)
print(arr == 30)
print(arr != 30)

[False False False  True  True]
[ True  True False False False]
[False False  True  True  True]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


# 3. Boolean Array

In [3]:
arr = np.array([10, 20, 30, 40, 50])

condition = arr > 30

print(condition)

[False False False  True  True]


# 4. Boolean Indexing

###Ab sabse important part.

###Hum Boolean array ko original array ke andar use kar sakte hain:

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])

[40 50]


# 5. Filter Values Greater Than a Number

In [5]:
arr = np.array([12, 45, 23, 67, 34, 89, 10])

result = arr[arr > 40]

print(result)

[45 67 89]


# 6. Filter Values Less Than a Number

In [6]:
arr = np.array([12, 45, 23, 67, 34, 89, 10])

print(arr[arr < 40])

[12 23 34 10]


# 7. Filter Exact Value

###Suppose hume sirf 30 find karna hai:

In [7]:
arr = np.array([10, 20, 30, 40, 30, 50])

print(arr[arr == 30])

[30 30]


# 8. Filtering with Range

##Suppose hume values chahiye:

###20 se greater
###AND
###50 se less

In [8]:
arr = np.array([10, 20, 25, 30, 45, 50, 60])

result = arr[(arr > 20) & (arr < 50)]

print(result)

[25 30 45]


# 9. AND Condition — &

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60])

result = arr[(arr >= 20) & (arr <= 50)]

print(result)

[20 30 40 50]


# 10. OR Condition — |

##Suppose hume values chahiye jo:

###20 se less
###OR
###50 se greater

In [10]:
arr = np.array([10, 20, 30, 40, 50, 60])

result = arr[(arr < 20) | (arr > 50)]

print(result)

[10 60]


# 11. NOT Condition — ~

###~ ka use condition ko reverse karne ke liye hota hai.

In [11]:
arr = np.array([10, 20, 30, 40, 50])

condition = arr > 30

print(condition)
print(~condition)

[False False False  True  True]
[ True  True  True False False]


# 12. Why Parentheses Are Important

##Ye sahi hai:

arr[(arr > 20) & (arr < 50)]

##Ye mat likhna:

arr[arr > 20 & arr < 50]

###Multiple NumPy conditions mein each condition ko parentheses mein rakhna safest and standard approach hai.

# 13. np.where()

###np.where() condition ke basis par values/indices determine karne ke liye useful hai.

In [12]:
arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 30)

print(result)

(array([3, 4]),)


# 14. np.where() with Two Values

###np.where() ka ek aur powerful use:

In [13]:
arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 30, 1, 0)

print(result)

[0 0 0 1 1]


# 15. Practical Example — Student Marks

###Ab ek real-world type example.

In [14]:
marks = np.array([45, 78, 92, 66, 35, 88, 54, 73])

passed = marks[marks >= 50]

print("Passed Students Marks:")
print(passed)

Passed Students Marks:
[78 92 66 88 54 73]


# 16. Find Students Scoring 80+


In [15]:
marks = np.array([45, 78, 92, 66, 35, 88, 54, 73])

top_students = marks[marks >= 80]

print(top_students)

[92 88]


# 17. Find Failed Students

###Passing marks = 50

In [16]:
marks = np.array([45, 78, 92, 66, 35, 88, 54, 73])

failed = marks[marks < 50]

print(failed)

[45 35]


# 18. Practical Example — Temperature

##Suppose temperatures:

temperature = np.array([
    22, 25, 31, 35, 28, 18, 40, 27
])

##Find temperatures above 30:

In [17]:
temperature = np.array([ 22, 25, 31, 35, 28, 18, 40, 27 ])
hot_days = temperature[temperature > 30]
print(hot_days)

[31 35 40]


# 19. Practical Example — Salary Filtering
###salary = np.array([
    25000,
    40000,
    55000,
    30000,
    75000,
    90000
])

###high_salary = salary[salary > 50000]

###print(high_salary)

In [19]:
salary = np.array([
    25000,
    40000,
    55000,
    30000,
    75000,
    90000
])
high_salary = salary[salary > 50000]
print(high_salary)

[55000 75000 90000]


# 20. Boolean Indexing with 2D Array

###Boolean filtering sirf 1D arrays ke liye nahi hai.

In [20]:
marks = np.array([
    [85, 90, 78],
    [45, 55, 60],
    [92, 88, 95]
])

print(marks[marks >= 80])

[85 90 92 88 95]


#📝 Day 25 Practice
##Q1 — Basic Filtering
arr = np.array([10, 25, 30, 45, 50, 65, 80])

##Find all values greater than 40.

In [21]:
arr = np.array([10, 25, 30, 45, 50, 65, 80])
print(arr[arr > 40])

[45 50 65 80]


#Q2 — Less Than

##Same array mein se values find karo jo 40 se less hain.

In [22]:
print(arr[arr<40])

[10 25 30]


#Q3 — Range Filtering

###Find values between 30 and 70.

###Both boundaries included honi chahiye.

In [23]:
print(arr[(arr>=30)&(arr<=70)])

[30 45 50 65]


#Q4 — Even Numbers

##Given:

arr = np.arange(1, 21)

###Boolean indexing ka use karke even numbers nikalo.

In [24]:
arr = np.arange(1, 21)
print(arr[arr%2==0])

[ 2  4  6  8 10 12 14 16 18 20]


#Q5 — Odd Numbers

###Same array se odd numbers nikalo.

In [25]:
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


#Q6 — Student Marks
marks = np.array([35, 67, 89, 42, 95, 76, 28, 81])

##Find:

###Passing marks (>= 50)
###Failing marks (< 50)
###Marks 80+

In [26]:
marks = np.array([35, 67, 89, 42, 95, 76, 28, 81])
print("Passing Marks:",marks[marks>=50])
print("Failing Marks:",marks[marks<50])
print("Marks 80+:",marks[marks>=80])

Passing Marks: [67 89 95 76 81]
Failing Marks: [35 42 28]
Marks 80+: [89 95 81]


#Q7 — AND Condition

##Given:

arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])

##Find values:

###20 se greater
###AND
###40 se less

In [27]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
print(arr[(arr>20)&(arr<40)])

[25 30 35]


#Q8 — OR Condition

##Same array se values find karo jo:

###20 se less
###OR
###40 se greater

In [28]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
print(arr[(arr>20)|(arr<40)])

[10 15 20 25 30 35 40 45 50]


#Q9 — np.where()

##Given:

marks = np.array([45, 72, 88, 39, 91, 56])

###np.where() ka use karke:

####marks >= 50 → 1
####marks < 50  → 0

###ka result generate karo.

In [29]:
marks=np.array([45, 72, 88, 39, 91, 56])
print(np.where(marks>=50,1,0))

[0 1 1 0 1 1]


#Q10 — Mini Practical

##Temperature data:

temperature = np.array([
    18, 22, 25, 31, 35, 28, 40, 19, 33, 27
])

##Find:

###Temperatures above 30
###Temperatures below 20
###Temperatures between 20 and 30, both included
###Temperatures above 25 and below 35

In [32]:
temperature = np.array([ 18, 22, 25, 31, 35, 28, 40, 19, 33, 27 ])
print("Temperatures above 30:",temperature[temperature>30])
print("Temperatures below 20:",temperature[temperature<20])
print("Temperatures between 20 and 30, both included:",temperature[(temperature>=20)&(temperature<=30)])
print("Temperatures above 25 and below 35:",temperature[(temperature>25)&(temperature<35)])

Temperatures above 30: [31 35 40 33]
Temperatures below 20: [18 19]
Temperatures between 20 and 30, both included: [22 25 28 27]
Temperatures above 25 and below 35: [31 28 33 27]
