# 🎯 Day 22 Goals

## Aaj ye concepts karenge:

Arithmetic operations

Scalar operations

Array-to-array operations

Comparison operations

Aggregate functions

sum()

min()

max()

mean()

std()

axis ka basic concept

Practical examples

Practice questions

# 1. Arithmatic Operations

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 2)

[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 5. 10. 15. 20.]


# 2. Array + Array

In [2]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


# 3. Comparison Operator

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)
print(arr < 30)
print(arr == 30)
print(arr >= 40)

[False False  True  True  True]
[ True  True False False False]
[False False  True False False]
[False False False  True  True]


# 4. Sum

In [5]:
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))

100


# 5. min() and max()

In [6]:
arr = np.array([10, 50, 20, 80, 30])

print(np.min(arr))
print(np.max(arr))

10
80


# 6. mean()

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))

30.0


# 7. std()

In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(np.std(arr))

14.142135623730951


# 8. axis()

In [9]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[50 70 90]
[ 60 150]


# axis=0 → columns ke according

# axis=1 → rows ke according

# Q1 — Arithmetic

## arr = np.array([5, 10, 15, 20, 25])

# Find:
### arr + 10
### arr * 2
### arr - 5

In [10]:
arr=np.array([5,10,15,20,25])
print(arr+10)
print(arr*2)
print(arr-5)

[15 20 25 30 35]
[10 20 30 40 50]
[ 0  5 10 15 20]


# Q2 — Two Arrays
## a = np.array([10, 20, 30, 40])
## b = np.array([1, 2, 3, 4])

# Find:

### addition
### subtraction
### multiplication

In [11]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


# Q3 — Comparison
## marks = np.array([35, 67, 89, 42, 91, 28])

# Find:

### marks greater than 50
### marks less than 40
### marks greater than or equal to 90

In [12]:
marks=np.array([35,67,89,42,91,28])
print(marks>50)
print(marks<40)
print(marks>=90)

[False  True  True False  True False]
[ True False False False False  True]
[False False False False  True False]


# Q4 — Statistics

## Given:

## marks = np.array([78, 85, 92, 67, 88, 95])

# Find:

### Total
### Minimum
### Maximum
### Average
### Standard Deviation

In [13]:
marks=np.array([78,85,92,67,88,95])
print(marks.sum())
print(marks.min())
print(marks.max())
print(marks.mean())
print(marks.std())

505
67
95
84.16666666666667
9.370461864580399


# Q5 — Axis 🔥

## Given:

marks = np.array([
    
    [80, 70, 90],
    
    [60, 85, 75],
    
    [95, 88, 92]
])

# Find:

###Total of the complete array
###Total of each column
###Total of each row
###Average of each row

In [14]:
marks = np.array([[80, 70, 90],[60, 85, 75],[95, 88, 92]])
print(marks.sum())
print(marks.sum(axis=0))
print(marks.sum(axis=1))
print(marks.mean(axis=1))

735
[235 243 257]
[240 220 275]
[80.         73.33333333 91.66666667]
