#🐍 Day 29 — NumPy Mathematical Functions & Vectorization

##NumPy ka main power sirf arrays banana nahi hai. NumPy arrays par fast mathematical operations bhi perform kar sakta hai.

##Aaj hum dekhenge ki bina manually loops likhe complete array par mathematical operations kaise perform karte hain.

#🎯 Day 29 Goals

###Aaj hum cover karenge:

###np.sqrt()
###np.abs()
###np.power()
###np.square()
###np.round()
###np.floor()
###np.ceil()
###np.sum()
###np.prod()
###np.clip()
###Vectorized operations
###NumPy Universal Functions — ufunc
###Practical data examples

#1️⃣ Import NumPy

In [1]:
import numpy as np

#2️⃣ np.sqrt() — Square Root

##np.sqrt() array ke har element ka square root calculate karta hai.

In [2]:
arr = np.array([1, 4, 9, 16, 25])

print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


#🧠 Important Point

###Agar array mein multiple values hain, NumPy har value par automatically operation apply kar deta hai.

#3️⃣ np.abs() — Absolute Value

##Absolute value negative sign hata deti hai.

In [3]:
arr = np.array([-10, -5, 0, 5, 10])

print(np.abs(arr))

[10  5  0  5 10]


#4️⃣ np.power() — Power Calculate Karna

##Har element ko kisi power par raise karne ke liye:

In [4]:
arr = np.array([2, 3, 4, 5])

print(np.power(arr, 2))

[ 4  9 16 25]


##Cube:

In [5]:
print(np.power(arr, 3))

[  8  27  64 125]


#5️⃣ np.square()

##Square calculate karne ka direct function:

In [6]:
arr = np.array([2, 4, 6, 8])

print(np.square(arr))

[ 4 16 36 64]


#6️⃣ np.round()

##Decimal values ko round karne ke liye:

In [7]:
arr = np.array([1.2345, 2.6789, 3.4567])

print(np.round(arr))

[1. 3. 3.]


##Specific Decimal Place:

In [8]:
print(np.round(arr, 2))

[1.23 2.68 3.46]


#7️⃣ np.floor()

##Value ko neeche wale integer ki taraf round karta hai.

In [9]:
arr = np.array([1.2, 2.7, 3.1, 4.9])

print(np.floor(arr))

[1. 2. 3. 4.]


#8️⃣ np.ceil()

##Value ko upar wale integer ki taraf round karta hai.

In [10]:
arr = np.array([1.2, 2.7, 3.1, 4.9])

print(np.ceil(arr))

[2. 3. 4. 5.]


#🧠 Difference
##1.2 → floor = 1
##1.2 → ceil  = 2

#9️⃣ np.sum()

##Array ke saare elements ka total:

In [11]:
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))

100


# 2-D Array:

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(np.sum(arr))

210


##Column-Wise:

In [13]:
print(np.sum(arr, axis=0))

[50 70 90]


##Row-Wise:

In [14]:
print(np.sum(arr, axis=1))

[ 60 150]


#🔟 np.prod()

##prod() ka matlab product.

In [15]:
arr = np.array([1, 2, 3, 4])

print(np.prod(arr))

24


#1️⃣1️⃣ np.clip()

##np.clip() values ko ek specific range ke andar limit karta hai.

In [16]:
arr = np.array([10, 25, 50, 75, 100, 125])

result = np.clip(arr, 20, 100)

print(result)

[ 20  25  50  75 100 100]


#🧠 Important Point
##np.clip(arr, minimum, maximum)

#Values:

###minimum se chhoti → minimum
###range ke andar → same
###maximum se badi → maximum

#1️⃣2️⃣ Vectorization 🔥

##Ye Day 29 ka important concept hai.

##Normally Python mein hum loop use kar sakte hain:

In [17]:
arr = np.array([10, 20, 30, 40])

result = []

for value in arr:
    result.append(value * 2)

print(result)

[np.int64(20), np.int64(40), np.int64(60), np.int64(80)]


##Lekin NumPy me Directly:

In [18]:
arr = np.array([10, 20, 30, 40])

print(arr * 2)

[20 40 60 80]


#🧠 Vectorization kya hai?

##Simple language mein:

###Vectorization means complete array par operation ek saath perform karna instead of manually processing each element using a loop.

####arr + 10
####arr - 5
####arr * 2
####arr / 10

#1️⃣3️⃣ Vectorization Example

In [19]:
arr = np.array([10, 20, 30, 40, 50])

print(arr + 5)
print(arr * 2)
print(arr / 10)

[15 25 35 45 55]
[ 20  40  60  80 100]
[1. 2. 3. 4. 5.]


#1️⃣4️⃣ NumPy Universal Functions — Ufuncs

##NumPy ke kuch functions ko Universal Functions (ufuncs) kaha jata hai.
###np.sqrt()
###np.abs()
###np.power()
###np.square()
###np.round()
###np.floor()
###np.ceil()

In [20]:
arr = np.array([1, 4, 9, 16])

print("Square Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Absolute:", np.abs(arr))

Square Root: [1. 2. 3. 4.]
Square: [  1  16  81 256]
Absolute: [ 1  4  9 16]


#1️⃣5️⃣ Practical Example — Student Marks

##Suppose marks decimal mein hain:

In [21]:
marks = np.array([78.456, 65.782, 91.349, 88.927, 72.514])

print("Original:", marks)
print("Rounded:", np.round(marks, 1))
print("Average:", np.mean(marks))

Original: [78.456 65.782 91.349 88.927 72.514]
Rounded: [78.5 65.8 91.3 88.9 72.5]
Average: 79.4056


#1️⃣6️⃣ Practical Example — Valid Marks Range

##Suppose kisi dataset mein kuch marks invalid hain:

In [22]:
marks = np.array([-5, 45, 78, 105, 92])

print(np.clip(marks, 0, 100))

[  0  45  78 100  92]


#1️⃣7️⃣ Practical Example — Product Prices

In [23]:
prices = np.array([
    199.4567,
    349.9999,
    499.1256,
    799.8765
])

print(np.round(prices, 2))

[199.46 350.   499.13 799.88]


#1️⃣8️⃣ Practical Example — Distance

##Suppose squared distances available hain:

In [24]:
squared_distance = np.array([4, 9, 16, 25, 36])

distance = np.sqrt(squared_distance)

print(distance)

[2. 3. 4. 5. 6.]


#1️⃣9️⃣ Combining Multiple Functions 🔥

##NumPy functions ko chain/combine bhi kar sakte hain.

In [25]:
data = np.array([
    -10.5,
    20.7,
    -30.2,
    40.8,
    50.4
])

result = np.abs(data)
result = np.round(result, 1)
result = np.clip(result, 0, 40)

print(result)

[10.5 20.7 30.2 40.  40. ]


#📝 Day 29 — Practice Questions + Code Solutions
#Q1. Square Root


In [27]:
arr = np.array([4, 9, 16, 25, 36])
result = np.sqrt(arr)
print(result)

[2. 3. 4. 5. 6.]


#Q2. Absolute Values

In [28]:
arr = np.array([-20, -10, -5, 0, 5, 10, 20])
result = np.abs(arr)
print(result)

[20 10  5  0  5 10 20]


#Q3. Square and Cube

In [29]:
arr = np.array([2, 3, 4, 5])
square = np.power(arr, 2)
cube = np.power(arr, 3)
print("Square:", square)
print("Cube:", cube)

Square: [ 4  9 16 25]
Cube: [  8  27  64 125]


#Q4. Rounding

In [30]:
arr = np.array([1.2345, 2.6789, 3.4567, 4.9876])
rounded_integer = np.round(arr)
rounded_2 = np.round(arr, 2)
print("Nearest Integer:", rounded_integer)
print("2 Decimal Places:", rounded_2)

Nearest Integer: [1. 3. 3. 5.]
2 Decimal Places: [1.23 2.68 3.46 4.99]


#Q5. Floor and Ceiling

In [31]:
arr = np.array([1.2, 2.7, 3.1, 4.9])
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)
print("Floor:", floor_values)
print("Ceil:", ceil_values)

Floor: [1. 2. 3. 4.]
Ceil: [2. 3. 4. 5.]


#Q6. Sum and Product

In [32]:
arr = np.array([2, 3, 4, 5])
total = np.sum(arr)
product = np.prod(arr)
print("Sum:", total)
print("Product:", product)

Sum: 14
Product: 120


#Q7. Clip Student Marks

In [33]:
marks = np.array([-10, 35, 67, 89, 105, 120])
valid_marks = np.clip(marks, 0, 100)
print(valid_marks)

[  0  35  67  89 100 100]


#Q8. Vectorization

In [34]:
arr = np.array([10, 20, 30, 40, 50])
multiply = arr * 2
addition = arr + 5
division = arr / 10
print("Multiply by 2:", multiply)
print("Add 5:", addition)
print("Divide by 10:", division)

Multiply by 2: [ 20  40  60  80 100]
Add 5: [15 25 35 45 55]
Divide by 10: [1. 2. 3. 4. 5.]


#Q9. Student Marks Analysis

In [35]:
import numpy as np

marks = np.array([78.456, 65.782, 91.349, 88.927, 72.514])

rounded_marks = np.round(marks, 2)
highest = np.max(marks)
lowest = np.min(marks)
average = np.mean(marks)

print("Rounded Marks:", rounded_marks)
print("Highest:", highest)
print("Lowest:", lowest)
print("Average:", average)

Rounded Marks: [78.46 65.78 91.35 88.93 72.51]
Highest: 91.349
Lowest: 65.782
Average: 79.4056


#Q10. Mini Data Processing

In [36]:
import numpy as np

arr = np.array([-15.678, 23.456, -8.234, 105.789, 67.891])

# Step 1: Absolute values
result = np.abs(arr)

# Step 2: Round
result = np.round(result, 2)

# Step 3: Clip between 0 and 100
result = np.clip(result, 0, 100)

print("Original:", arr)
print("Processed:", result)

Original: [-15.678  23.456  -8.234 105.789  67.891]
Processed: [ 15.68  23.46   8.23 100.    67.89]
