#🐼 Day 31 — Pandas Introduction & Series

##Bhai, aaj se Pandas start. 🔥
##Aur ek important change: NumPy ki tarah sirf artificial examples nahi rakhenge. Pandas phase se hi CSV/real-data mindset start karenge, taaki Day 51–60 tak proper Kaggle datasets par confidently kaam kar sakein.

##Pandas ka main kaam hai tabular data ko load, inspect, clean aur analyze karna.

#🎯 Day 31 Goals

##Aaj hum seekhenge:

###Pandas kya hai?
###Pandas kyun use hota hai?
###Pandas install/import
###Series kya hoti hai?
###Series create karna
###Series indexing
###Custom index
###Series slicing
###Series properties
###Series mathematical operations
###Boolean filtering
###Series with NumPy
###Basic real-data style example

#1️⃣ Pandas Kya Hai?

##Pandas Python ki ek powerful library hai jo mainly structured/tabular data ke saath kaam karne ke liye use hoti hai.

##Example tabular data:

Name       Age    Marks

Sagar      20     85

Rahul      21     78

Aman       20     91

##Pandas ki help se hum:

###CSV load
   ↓
###Data inspect
   ↓
###Data clean
   ↓
###Filter
   ↓
###Analyze
   ↓
###Transform
   ↓
###Insights

###kar sakte hain.

#🧠 Important Point

##NumPy ka focus:

###Numerical arrays

##Pandas ka focus:

###Structured/tabular data

#2️⃣ Pandas Import Karna

##Google Colab me generally Pandas already installed hota hai.

In [1]:
import pandas as pd

In [2]:
import pandas as pd

print(pd.__version__)

2.2.3


#3️⃣ Pandas ke Two Main Data Structures

##Pandas ke do major data structures hain:

###Pandas
###  │
###  ├── Series
###  │
###  └── DataFrame

#Series

##One-dimensional data.

####10
####20
####30
####40
####50

#DataFrame

##Two-dimensional tabular data.

####Name    Age    Marks
####A       20     80
####B       21     75
####C       20     90

##Aaj → Series

##Aage → DataFrame

#4️⃣ First Pandas Series

In [3]:
import pandas as pd

marks = pd.Series([78, 85, 92, 67, 74])

print(marks)

0    78
1    85
2    92
3    67
4    74
dtype: int64


#Yahan:

0  → index

78 → value

#5️⃣ Understanding Series

In [4]:
marks = pd.Series([78, 85, 92, 67, 74])

print("Values:")
print(marks.values)

print("\nIndex:")
print(marks.index)

Values:
[78 85 92 67 74]

Index:
RangeIndex(start=0, stop=5, step=1)


#🧠 Important

##Series internally:

###Index → Value
####  0   → 78
####  1   → 85
####  2   → 92
####  3   → 67
####  4   → 74

#6️⃣ Accessing Series Elements

##Normal indexing:

In [5]:
marks = pd.Series([78, 85, 92, 67, 74])

print(marks[0])
print(marks[2])
print(marks[4])

78
92
74


#7️⃣ Negative Indexing

##Python lists me:
arr[-1]

##last element deta hai.

#But Pandas Series me .iloc use karna safer and clearer hai:

In [6]:
marks = pd.Series([78, 85, 92, 67, 74])

print(marks.iloc[-1])
print(marks.iloc[-2])

74
67


#🧠 Important

##iloc = position based indexing

###marks.iloc[0]
###marks.iloc[2]
###marks.iloc[-1]

#8️⃣ Custom Index

##Hum apne indexes bhi define kar sakte hain.

In [7]:
marks = pd.Series(
    [78, 85, 92, 67, 74],
    index=["Maths", "Python", "DBMS", "CN", "OS"]
)

print(marks)

Maths     78
Python    85
DBMS      92
CN        67
OS        74
dtype: int64


##Ab hum label se value access kar sakte hain:

In [8]:
print(marks["Python"])
print(marks["DBMS"])

85
92


#9️⃣ .loc — Label Based Indexing

##Custom labels ke saath .loc use karna important hai.

In [9]:
marks = pd.Series(
    [78, 85, 92, 67, 74],
    index=["Maths", "Python", "DBMS", "CN", "OS"]
)

print(marks.loc["Python"])
print(marks.loc["DBMS"])

85
92


#🧠 Remember
##iloc → position
##loc  → label

#🔟 Series Slicing

In [10]:
marks = pd.Series([78, 85, 92, 67, 74])

print(marks[1:4])

1    85
2    92
3    67
dtype: int64


##Using .iloc:

In [11]:
print(marks.iloc[1:4])

1    85
2    92
3    67
dtype: int64


#1️⃣1️⃣ Series Properties

##Pandas Series ki important properties:

In [12]:
marks = pd.Series([78, 85, 92, 67, 74])

print("Shape:", marks.shape)
print("Size:", marks.size)
print("Dimension:", marks.ndim)
print("Data Type:", marks.dtype)

Shape: (5,)
Size: 5
Dimension: 1
Data Type: int64


#🧠 NumPy se connection

##Ye properties hum NumPy me already kar chuka hai.

###NumPy Array
  # ↓
###Pandas Series
   #  ↓
###Same numerical foundation

#1️⃣2️⃣ Series Mathematical Operations

In [13]:
marks = pd.Series([50, 60, 70, 80, 90])

print(marks + 5)
print(marks * 2)
print(marks / 10)

0    55
1    65
2    75
3    85
4    95
dtype: int64
0    100
1    120
2    140
3    160
4    180
dtype: int64
0    5.0
1    6.0
2    7.0
3    8.0
4    9.0
dtype: float64


#🧠 Important

##Pandas Series bhi vectorized operations support karti hai.

#1️⃣3️⃣ Series Statistical Functions

In [14]:
marks = pd.Series([78, 85, 92, 67, 74])

print("Sum:", marks.sum())
print("Mean:", marks.mean())
print("Maximum:", marks.max())
print("Minimum:", marks.min())
print("Standard Deviation:", marks.std())

Sum: 396
Mean: 79.2
Maximum: 92
Minimum: 67
Standard Deviation: 9.67987603226405


#🧠 Mind Template
###sum()  → total
###mean() → average
###max()  → highest
###min()  → lowest
###std()  → variation

#1️⃣4️⃣ Boolean Filtering

##Ab Pandas ka important feature.

In [15]:
marks = pd.Series([45, 67, 89, 72, 95, 54, 81])

high_marks = marks[marks > 75]

print(high_marks)

2    89
4    95
6    81
dtype: int64


#Notice karo:

##value ke saath original index bhi preserve hua.

#1️⃣5️⃣ Multiple Conditions

##Suppose marks between 60 and 90 chahiye.

In [16]:
marks = pd.Series([45, 67, 89, 72, 95, 54, 81])
result = marks[(marks >= 60) & (marks <= 90)]
print(result)

1    67
2    89
3    72
6    81
dtype: int64


#🧠 Important

##Pandas me bhi:

###&
###|
###~

###use karte hain

#1️⃣6️⃣ describe() — Quick Summary

##Pandas ka very useful function:

In [17]:
marks = pd.Series([78, 85, 92, 67, 74, 88, 91, 56])

print(marks.describe())

count     8.000000
mean     78.875000
std      12.699128
min      56.000000
25%      72.250000
50%      81.500000
75%      88.750000
max      92.000000
dtype: float64


#🧠 Ye important hai

##describe() ek quick statistical summary deta hai.

##Real dataset analysis me ye bahut frequently useful hoga.

#1️⃣7️⃣ Series with NumPy

##Pandas aur NumPy ek saath kaam karte hain.

In [18]:
import numpy as np
import pandas as pd

marks = pd.Series([64, 81, 92, 75, 88])

print(np.sqrt(marks))

0    8.000000
1    9.000000
2    9.591663
3    8.660254
4    9.380832
dtype: float64


#🧠 Important

##Aage Data Analysis me hum frequently use karenge:

###Pandas → Data handling
###NumPy  → Numerical operations

##Dono complementary hain.

#1️⃣8️⃣ Practical Example — Student Marks

##Ab thoda real-data style.

In [19]:
import pandas as pd

marks = pd.Series(
    [78, 85, 92, 67, 74],
    index=["Sagar", "Rahul", "Aman", "Priya", "Neha"]
)

print("All Marks:")
print(marks)

print("\nAverage Marks:")
print(marks.mean())

print("\nHighest Marks:")
print(marks.max())

print("\nStudents above 80:")
print(marks[marks > 80])

All Marks:
Sagar    78
Rahul    85
Aman     92
Priya    67
Neha     74
dtype: int64

Average Marks:
79.2

Highest Marks:
92

Students above 80:
Rahul    85
Aman     92
dtype: int64


#1️⃣9️⃣ Series from Dictionary

##Dictionary se directly Series bana sakte hain:

In [20]:
import pandas as pd

marks = {
    "Maths": 85,
    "Python": 92,
    "DBMS": 78,
    "CN": 88
}

series = pd.Series(marks)

print(series)

Maths     85
Python    92
DBMS      78
CN        88
dtype: int64


#🧠 Important

##Dictionary:

###key   → index
###value → Series value

#2️⃣0️⃣ Missing Value Introduction

##Real datasets me missing values milna bahut common hai.

In [21]:
marks = pd.Series([85, 92, None, 78, 88])

print(marks)

0    85.0
1    92.0
2     NaN
3    78.0
4    88.0
dtype: float64


##NaN means:

Not a Number / missing value

In [22]:
print(marks.isna())

0    False
1    False
2     True
3    False
4    False
dtype: bool


#Missing values ko properly handle karna hum Pandas ke later days me detail me karenge.

#🧠 Day 31 Mind Template
##PANDAS
###↓
###Series
###↓
##Create
##  ├── List
##  └── Dictionary
###  ↓
##Access
##  ├── iloc → position
##  └── loc  → label
###  ↓
##Inspect
##  ├── shape
##  ├── size
##  ├── ndim
##  └── dtype
###  ↓
##Analyze
##  ├── sum()
##  ├── mean()
##  ├── min()
##  ├── max()
##  └── describe()
###  ↓
##Filter
##  └── Series[condition]
###  ↓
##Missing Data
##  └── isna()

#📝 Day 31 Practice
##Q1

#Create a Pandas Series:

10, 20, 30, 40, 50

##Print:

###Values
###Index
###Shape
###Size
###Dimension
###Data type

In [26]:
number=pd.Series([10,20,30,40,50])
print(number.values)
print(number.index)
print(number.shape)
print(number.size)
print(number.ndim)
print(number.dtype)

[10 20 30 40 50]
RangeIndex(start=0, stop=5, step=1)
(5,)
5
1
int64


#Q2

##Create a Series containing:

85, 72, 91, 64, 88

#Find:

###Sum
###Average
###Maximum
###Minimum
###Standard deviation

In [28]:
num=pd.Series([85,72,91,64,88])
print("Sum:",num.sum())
print("Average:",num.mean())
print("Maximum:",num.max())
print("Minimum:",num.min())
print("Standard Deviation:",num.std())

Sum: 400
Average: 80.0
Maximum: 91
Minimum: 64
Standard Deviation: 11.510864433221338


#Q3

##Create a Series with custom indexes:

###Maths
###Python
###DBMS
###CN
###OS

#With marks:

###78
###92
###85
###67
###88

##Access Python and DBMS marks using .loc.

In [32]:
marks=pd.Series([78,92,85,67,88],index=["Maths","Python","DBMS","CN","OS"])
print(marks.loc["Python"])
print(marks.loc["DBMS"])

92
85


#Q4

##Using the same Series, access:

###First element
###Third element
###Last element

##using .iloc.

In [33]:
print(marks.iloc[0])
print(marks.iloc[2])
print(marks.iloc[-1])

78
85
88


#Q5

##Given:

marks = pd.Series([45, 67, 89, 72, 95, 54, 81])

##Find all marks:

###greater than 70

In [34]:
marks=pd.Series([45,67,89,72,95,54,81])
print(marks[marks>70])

2    89
3    72
4    95
6    81
dtype: int64


#Q6

##Using the same Series, find marks between:

###60 and 90

In [35]:
print(marks[(marks>=60) & (marks<=90)])

1    67
2    89
3    72
6    81
dtype: int64


#Q7

##Create a Series from this dictionary:

{
    "Sagar": 85,
    "Rahul": 72,
    "Aman": 91,
    "Priya": 88
}

##Find the average and students scoring above 80.

In [39]:
import pandas as pd
student = pd.Series({ "Sagar": 85, "Rahul": 72, "Aman": 91, "Priya": 88 })
print("--- Student Series ---")
print(student)
Average = student.mean()
print("\n--- Average Marks ---")
print(Average)
print("\n--- Students Scoring > 80 ---")
print(student[student > 80])

--- Student Series ---
Sagar    85
Rahul    72
Aman     91
Priya    88
dtype: int64

--- Average Marks ---
84.0

--- Students Scoring > 80 ---
Sagar    85
Aman     91
Priya    88
dtype: int64


#Q8

##Create a Series containing:

85, 92, None, 78, None, 88

##Find which values are missing using:

##isna()

In [41]:
marks=pd.Series([85,92,None,78,None,88])
print(marks.isna())

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool


#Q9

##Create a Series of 10 random marks using NumPy and convert/use it as a Pandas Series.

##Find:

###Mean
###Maximum
###Minimum
###Students/values above mean

In [45]:
import numpy as np
import pandas as pd
num=np.random.randint(1,51,size=10)
print(num)
marks=pd.Series(num)
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())
print("Students/values above mean:",marks[marks>marks.mean()])

[48 30 34  6 28 34 14 26 21 30]
Mean: 27.1
Maximum: 48
Minimum: 6
Students/values above mean: 0    48
1    30
2    34
4    28
5    34
9    30
dtype: int64


#Q10 — 🔥 Mini Challenge

##Create a Student Marks Analyzer using Pandas Series.

##Your program should:

##Create student marks
###       ↓
##Display marks
###       ↓
##Calculate average
###       ↓
##Find highest marks
###       ↓
##Find lowest marks
###       ↓
##Filter students above 80
###       ↓
##Show statistical summary

In [46]:
import pandas as pd

marks = pd.Series(
    [85, 72, 91, 64, 78],
    index=["Rahul", "Aman", "Priya", "Neha", "Rohit"]
)

print("Student Marks:")
print(marks)

print("\nAverage Marks:", marks.mean())
print("Highest Marks:", marks.max())
print("Lowest Marks:", marks.min())

print("\nStudents scoring above 75:")
print(marks[marks > 75])

print("\nStudents scoring 80 or above:")
print(marks[marks >= 80])

Student Marks:
Rahul    85
Aman     72
Priya    91
Neha     64
Rohit    78
dtype: int64

Average Marks: 78.0
Highest Marks: 91
Lowest Marks: 64

Students scoring above 75:
Rahul    85
Priya    91
Rohit    78
dtype: int64

Students scoring 80 or above:
Rahul    85
Priya    91
dtype: int64
