#🐍 Day 30 — NumPy Consolidation & Practical Data Processing

##Bhai, Day 30 NumPy ka final day hai. Aaj hum alag-alag concepts ko individually nahi, balki combine karke ek complete data-processing workflow banayenge.

##Ab tak humne arrays, indexing, slicing, filtering, reshaping, sorting, joining, random data, mathematical functions aur vectorization cover kiya hai. Aaj in sabko ek saath use karenge.

#🎯 Day 30 Goals

##Aaj hum seekhenge:

###NumPy concepts ka quick revision
###Multiple operations ko combine karna
###Data cleaning with NumPy
###Filtering + statistics
###Sorting + indexing
###Reshaping data
###Vectorized calculations
###Practical student dataset
###Practical sales dataset
###Complete NumPy mini data-processing project

#1️⃣ NumPy Quick Revision

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

[10 20 30 40 50]
Shape: (5,)
Dimension: 1
Size: 5
Data Type: int64


#2️⃣ Vectorized Operations

##NumPy ka major advantage hai ki hum poore array par directly operation kar sakte hain.

In [3]:
marks = np.array([50, 60, 70, 80, 90])
print("Original:", marks)
print("After +5:", marks + 5)
print("After *2:", marks * 2)
print("After /10:", marks / 10)

Original: [50 60 70 80 90]
After +5: [55 65 75 85 95]
After *2: [100 120 140 160 180]
After /10: [5. 6. 7. 8. 9.]


#3️⃣ Mathematical Functions

##Ab multiple mathematical functions combine karte hain.

In [4]:
arr = np.array([4, 9, 16, 25, 36])

print("Square Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Power 3:", np.power(arr, 3))

Square Root: [2. 3. 4. 5. 6.]
Square: [  16   81  256  625 1296]
Power 3: [   64   729  4096 15625 46656]


#🧠 Important Point

##Common functions:

###np.sqrt()
###np.abs()
###np.square()
###np.power()
###np.round()
###np.floor()
###np.ceil()

#4️⃣ Statistics

##Data analysis me statistics bahut important hai.

In [5]:
marks = np.array([78, 65, 91, 88, 72])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Total: 394
Average: 78.8
Highest: 91
Lowest: 65
Standard Deviation: 9.703607576566563


#🧠 Mind Template

##Jab dataset ka basic analysis karna ho:

###Total → np.sum()
###Average → np.mean()
###Highest → np.max()
###Lowest → np.min()
###Variation → np.std()

#5️⃣ Boolean Filtering

##Suppose hume sirf 75 se zyada marks chahiye.

In [6]:
marks = np.array([45, 67, 89, 72, 95, 54, 81])

high_marks = marks[marks > 75]

print(high_marks)

[89 95 81]


##Multiple Conditions:

In [7]:
marks = np.array([45, 67, 89, 72, 95, 54, 81])

result = marks[(marks >= 60) & (marks <= 90)]

print(result)

[67 89 72 81]


#🧠 Important Point

##NumPy filtering:

arr[condition]

##Multiple conditions:

arr[(condition1) & (condition2)]

#6️⃣ Cleaning Invalid Data Using np.clip()

##Real datasets me kabhi-kabhi invalid values aa sakti hain.

In [8]:
marks = np.array([-10, 45, 67, 89, 105, 120])

clean_marks = np.clip(marks, 0, 100)

print("Original:", marks)
print("Cleaned:", clean_marks)

Original: [-10  45  67  89 105 120]
Cleaned: [  0  45  67  89 100 100]


#🧠 Important Point

##np.clip() values ko given range ke andar rakhta hai.

##np.clip(array, minimum, maximum)

#7️⃣ Sorting Data

In [9]:
marks = np.array([78, 45, 91, 67, 85])

sorted_marks = np.sort(marks)

print("Original:", marks)
print("Sorted:", sorted_marks)

Original: [78 45 91 67 85]
Sorted: [45 67 78 85 91]


##Descending:

In [10]:
descending = np.sort(marks)[::-1]

print(descending)

[91 85 78 67 45]


#8️⃣ Finding Position of Highest Value

In [11]:
marks = np.array([78, 45, 91, 67, 85])

highest_index = np.argmax(marks)
lowest_index = np.argmin(marks)

print("Highest Index:", highest_index)
print("Lowest Index:", lowest_index)

Highest Index: 2
Lowest Index: 1


##Actual Marks:

In [12]:
print("Highest Marks:", marks[highest_index])
print("Lowest Marks:", marks[lowest_index])

Highest Marks: 91
Lowest Marks: 45


#9️⃣ Reshaping Data

Suppose humare paas 12 values hain:

In [13]:
data = np.arange(1, 13)

print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


##Ab ise 3×4 matrix me convert karte hain:

In [14]:
matrix = data.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#🧠 Important Point

##Total elements same rehne chahiye.

###12 elements

###3 × 4 = 12 ✅
###4 × 3 = 12 ✅
###2 × 6 = 12 ✅

###5 × 3 = 15 ❌

#🔟 2D Data Analysis

##Ab ek student dataset jaisa data banate hain.

##Columns:
Maths | Python | DBMS | CN

In [15]:
marks = np.array([
    [78, 85, 72, 80],
    [65, 70, 68, 75],
    [90, 92, 88, 95],
    [55, 60, 58, 62],
    [82, 79, 85, 88]
])

print(marks)

[[78 85 72 80]
 [65 70 68 75]
 [90 92 88 95]
 [55 60 58 62]
 [82 79 85 88]]


##Subject-Wise Arrange:

In [16]:
subject_average = np.mean(marks, axis=0)

print(subject_average)

[74.  77.2 74.2 80. ]


##Student-Wise Arrange:

In [17]:
student_average = np.mean(marks, axis=1)

print(student_average)

[78.75 69.5  91.25 58.75 83.5 ]


#🧠 Remember
##axis=0 → columns
##axis=1 → rows

#1️⃣1️⃣ Find Top Student

In [18]:
student_average = np.mean(marks, axis=1)

top_student_index = np.argmax(student_average)

print("Top Student Index:", top_student_index)
print("Top Student Average:", student_average[top_student_index])

Top Student Index: 2
Top Student Average: 91.25


#🧠 Important Point

##Yahan humne multiple concepts combine kiye:

##2D Array
   ↓
##np.mean(axis=1)
   ↓
##Student averages
   ↓
##np.argmax()
   ↓
##Top student

#1️⃣2️⃣ Practical Example — Student Performance

##Ab ek complete small analysis banate hain.

In [19]:
import numpy as np

marks = np.array([
    [78, 85, 72, 80],
    [65, 70, 68, 75],
    [90, 92, 88, 95],
    [55, 60, 58, 62],
    [82, 79, 85, 88]
])

student_average = np.mean(marks, axis=1)

print("Student Averages:")
print(np.round(student_average, 2))

print("\nHighest Average:")
print(np.max(student_average))

print("\nLowest Average:")
print(np.min(student_average))

print("\nOverall Average:")
print(np.mean(marks))

Student Averages:
[78.75 69.5  91.25 58.75 83.5 ]

Highest Average:
91.25

Lowest Average:
58.75

Overall Average:
76.35


#🧠 Isme kya-kya use hua?
###np.array()
###np.mean()
###axis
###np.round()
###np.max()

#1️⃣3️⃣ Practical Example — Sales Data

##Ab student data ke alawa ek business-style example.

In [20]:
sales = np.array([12000, 15000, 11000, 18000, 22000, 17000, 25000])

print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))

Total Sales: 120000
Average Sales: 17142.85714285714
Highest Sales: 25000
Lowest Sales: 11000


##Find days with sales above 15,000

In [21]:
high_sales = sales[sales > 15000]

print(high_sales)

[18000 22000 17000 25000]


##Sort sales

In [22]:
sorted_sales = np.sort(sales)

print(sorted_sales)

[11000 12000 15000 17000 18000 22000 25000]


#1️⃣4️⃣ Practical Data Cleaning Pipeline

##Ab ek important mini pipeline.

##Suppose data:

###data = np.array([-20.567, 45.789, 78.345, 105.678, 67.891])

#Hume:

##Negative values remove/positive magnitude
##2 decimal rounding
##0–100 range maintain

In [23]:
data = np.array([-20.567, 45.789, 78.345, 105.678, 67.891])
data = np.array([-20.567, 45.789, 78.345, 105.678, 67.891])

data = np.abs(data)
data = np.round(data, 2)
data = np.clip(data, 0, 100)

print(data)

[ 20.57  45.79  78.34 100.    67.89]


#🧠 Data Processing Mindset
##Raw Data
   ↓
##Inspect
   ↓
##Transform
   ↓
##Clean
   ↓
##Filter
   ↓
##Analyze
   ↓
##Result

#1️⃣5️⃣ Complete NumPy Mini Project

##Ab ek small Student Performance Analyzer banate hain.

In [24]:
import numpy as np

# Student marks
marks = np.array([
    [78, 85, 72, 80],
    [65, 70, 68, 75],
    [90, 92, 88, 95],
    [55, 60, 58, 62],
    [82, 79, 85, 88]
])

# Student average
student_avg = np.mean(marks, axis=1)

# Subject average
subject_avg = np.mean(marks, axis=0)

# Top student
top_index = np.argmax(student_avg)

# Lowest student
lowest_index = np.argmin(student_avg)

# Passing students
passing_students = student_avg >= 60

print("===== STUDENT PERFORMANCE =====")

print("\nStudent Averages:")
print(np.round(student_avg, 2))

print("\nSubject Averages:")
print(np.round(subject_avg, 2))

print("\nTop Student Index:", top_index)
print("Top Student Average:", round(student_avg[top_index], 2))

print("\nLowest Student Index:", lowest_index)
print("Lowest Student Average:", round(student_avg[lowest_index], 2))

print("\nPassing Status:")
print(passing_students)

print("\nOverall Average:")
print(round(np.mean(marks), 2))

===== STUDENT PERFORMANCE =====

Student Averages:
[78.75 69.5  91.25 58.75 83.5 ]

Subject Averages:
[74.  77.2 74.2 80. ]

Top Student Index: 2
Top Student Average: 91.25

Lowest Student Index: 3
Lowest Student Average: 58.75

Passing Status:
[ True  True  True False  True]

Overall Average:
76.35


#🧠 Is project me humne use kiya:
##NumPy Array
↓
##2D Array
↓
##axis
↓
##Mean
↓
##Argmax
↓
##Argmin
↓
##Boolean Filtering
↓
##Rounding

#🧠 Day 30 Final NumPy Mind Template
##1. Data → np.array()

##2. Understand
   → shape
   → ndim
   → size
   → dtype

##3. Select
   → indexing
   → slicing
   → boolean filtering

##4. Transform
   → reshape
   → arithmetic
   → mathematical functions
   → vectorization

##5. Clean
   → abs
   → round
   → clip

##6. Analyze
   → sum
   → mean
   → min
   → max
   → std

##7. Search
   → argmax
   → argmin
   → where
   → unique

##8. Organize
   → sort
   → concatenate
   → split

##9. Final Result
   → filtered / cleaned / analyzed data

#📝 Day 30 Practice
##Q1

###Create an array:

[10, 20, 30, 40, 50, 60]

##Find:

###Sum
###Mean
###Maximum
###Minimum
###Standard deviation

In [25]:
arr=np.array([10,20,30,40,50,60])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Maximum:",np.max(arr))
print("Minimum:",np.min(arr))

Sum: 210
Mean: 35.0
Maximum: 60
Minimum: 10


#Q2

##Given:

arr = np.array([5, 10, 15, 20, 25])

##Perform:

###× 3
###+ 10
###÷ 5
###square

In [26]:
arr=np.array([5,10,15,20,25])
print(arr*3)
print(arr+10)
print(arr/5)
print(arr**2)

[15 30 45 60 75]
[15 20 25 30 35]
[1. 2. 3. 4. 5.]
[ 25 100 225 400 625]


#Q3

##Given:

marks = np.array([45, 67, 89, 32, 91, 76, 54, 88])

##Find:

###Marks above 75
###Marks between 50 and 80
###Highest marks
###Lowest marks
###Sorted marks

In [27]:
marks=np.array([45,67,89,32,91,76,54,88])
print(marks[marks>75])
print(marks[(marks>=50) & (marks<=80)])
Highest=np.max(marks)
Lowest=np.min(marks)
print("Highest Marks:",Highest)
print("Lowest Marks:",Lowest)
Sorted=np.sort(marks)
print("Sorted Marks:",Sorted)

[89 91 76 88]
[67 76 54]
Highest Marks: 91
Lowest Marks: 32
Sorted Marks: [32 45 54 67 76 88 89 91]


#Q4

##Create numbers from 1 to 20 and reshape them into:

###4 × 5

##Then find row-wise and column-wise sums.

In [32]:
import numpy as np

arr = np.arange(1, 21)

print(arr)

matrix = arr.reshape(4, 5)

print(matrix)

print("Column-wise sum:", np.sum(matrix, axis=0))
print("Row-wise sum:", np.sum(matrix, axis=1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Column-wise sum: [34 38 42 46 50]
Row-wise sum: [15 40 65 90]


#Q5

##Create a 5×4 student marks array and calculate:

###Each student's average
###Each subject's average
###Top student's index
###Lowest student's index
###Students having average ≥ 60

In [33]:
marks = np.array([
    [78, 85, 72, 80],
    [65, 70, 68, 75],
    [90, 92, 88, 95],
    [55, 60, 58, 62],
    [82, 79, 85, 88]
])
# Student average
student_avg = np.mean(marks, axis=1)

# Subject average
subject_avg = np.mean(marks, axis=0)

# Top student
top_index = np.argmax(student_avg)

# Lowest student
lowest_index = np.argmin(student_avg)

print("\nStudent Averages:")
print(np.round(student_avg, 2))

print("\nSubject Averages:")
print(np.round(subject_avg, 2))

print("\nTop Student Index:", top_index)
print("Top Student Average:", round(student_avg[top_index], 2))

print("\nLowest Student Index:", lowest_index)
print("Lowest Student Average:", round(student_avg[lowest_index], 2))

passing_students = student_average >= 60
print(passing_students)

print(student_average[student_average >= 60])


Student Averages:
[78.75 69.5  91.25 58.75 83.5 ]

Subject Averages:
[74.  77.2 74.2 80. ]

Top Student Index: 2
Top Student Average: 91.25

Lowest Student Index: 3
Lowest Student Average: 58.75
[ True  True  True False  True]
[78.75 69.5  91.25 83.5 ]


#Q6

##Given:

data = np.array([-5, 20, 45, 110, 75, -10, 90])

##Clean it using:

###abs → round → clip

In [34]:
data=np.array([-5,20,45,110,75,-10,90])
data=np.abs(data)
data=np.round(data,2)
data=np.clip(data,0,100)
print(data)

[  5  20  45 100  75  10  90]


#Q7

##Generate 20 random integers between 1 and 100.

##Find:

###Mean
###Maximum
###Minimum
###Values above mean
###Sorted array

In [38]:
arr=np.random.randint(1,101,20)
print(arr)
print("Mean:",np.mean(arr))
print("Maximum:",np.max(arr))
print("Minimum:",np.min(arr))
print("Values above mean:",arr[arr>np.mean(arr)])

[19 94 34 43 11 58 14 53 70 95 31 97 86 97 61 42 40 92 99 55]
Mean: 59.55
Maximum: 99
Minimum: 11
Values above mean: [94 70 95 97 86 97 61 92 99]


#Q8

##Create two arrays of 5 student marks each and combine them into one array using NumPy.

In [39]:
marks1=np.array([1,2,3,4,5])
marks2=np.array([ 6,7,8,9,10])
marks=np.concatenate((marks1,marks2))
print(marks)

[ 1  2  3  4  5  6  7  8  9 10]


#Q9

##Create a sales array for 7 days.

##Find:

###Total sales
###Average sales
###Highest sales
###Lowest sales
###Days having sales above average

In [40]:
arr=np.array([10,20,30,40,50,60,70])
print("Total sales:",np.sum(arr))
print("Average sales:",np.mean(arr))
print("Highest sales:",np.max(arr))
print("Lowest Sales:",np.min(arr))
print("Days having sales above average:",arr[arr>np.mean(arr)])

Total sales: 280
Average sales: 40.0
Highest sales: 70
Lowest Sales: 10
Days having sales above average: [50 60 70]


#Q10 — 🔥 Mini Challenge

##Create a Student Performance Analyzer with at least:

###5 students
###4 subjects

##Your program should calculate:

###Student-wise average
###Subject-wise average
###Highest-performing student
###Lowest-performing student
###Overall class average
###Passing students
###Sorted student averages

In [42]:
marks = np.array([
    [78, 85, 72, 80],
    [65, 70, 68, 75],
    [90, 92, 88, 95],
    [55, 60, 58, 62],
    [82, 79, 85, 88]
])
student_average = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)
top_index = np.argmax(student_average)
lowest_index = np.argmin(student_average)
passing_students = student_average >= 60
print("\nStudent Averages:")
print(np.round(student_average, 2))
print("\nSubject Averages:")
print(np.round(subject_average, 2))
print("\nTop Student Index:", top_index)
print("Top Student Average:", round(student_average[top_index], 2))
print("\nLowest Student Index:", lowest_index)
print("Lowest Student Average:", round(student_average[lowest_index], 2))
print("\nPassing Status:")
print(passing_students)
print("\nOverall Average:")
print(round(np.mean(marks), 2))
print("\nSorted Student Averages:")
print(np.sort(student_average))


Student Averages:
[78.75 69.5  91.25 58.75 83.5 ]

Subject Averages:
[74.  77.2 74.2 80. ]

Top Student Index: 2
Top Student Average: 91.25

Lowest Student Index: 3
Lowest Student Average: 58.75

Passing Status:
[ True  True  True False  True]

Overall Average:
76.35

Sorted Student Averages:
[58.75 69.5  78.75 83.5  91.25]
