In [1]:
import numpy as np

print(np.__version__)

2.1.3


# 🎯 Day 21 Goals

## Aaj hum ye cover karenge:

1. NumPy kya hai?

2. NumPy ki zarurat kyun padti hai?

3. Installation & import

4. Python List vs NumPy Array

5. 1D NumPy Array

6. 2D NumPy Array

7. Array properties:

8. shape

9. ndim

10. size

11. dtype

12. Basic indexing & slicing

13. Practice questions

# 1. NumPy kya hai?

NumPy = Numerical Python

Ye Python ki ek library hai jo mainly numbers, arrays aur numerical calculations ke liye use hoti hai.

In [2]:
# Normal Python List:
numbers=[10,20,30,40,50]

# NumPy Array:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

NumPy arrays ka sabse important concept hai:

NumPy ek powerful multidimensional array structure provide karta hai.

Ye Data Science, Machine Learning, scientific computing etc. mein bahut commonly use hota hai.

# 2. NumPy kyun seekh rahe hain?

NumPy

  ↓

Pandas

  ↓

Matplotlib + Seaborn

  ↓

Data Analysis Projects

  ↓

Machine Learning

In [3]:
# NumPy ke saath hum directly operations kar sakte hain:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 10)

[20 30 40 50]


# 3. Installation

# VS Code terminal mein:

python -m pip install numpy


# Agar Windows mein python command issue kare:


py -m pip install numpy


# Check karne ke liye:


python -c "import numpy as np; print(np.__version__)"


## Agar version print ho gaya → NumPy successfully installed ✅

# 4. NumPy Import

Almost har NumPy program mein tum ye dekhoge:

In [4]:
import numpy as np

In [5]:
# Yahan:
"""numpy → library ka naam
np    → short alias"""

'numpy → library ka naam\nnp    → short alias'

# 5. NumPy Array banana

## Sabse basic:

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [7]:
arr = np.array([10, 20, 30, 40, 50])
# np.array() list ko NumPy array mein convert kar deta hai.

# 6. 1D Array

In [8]:
arr = np.array([10, 20, 30, 40, 50])

In [9]:
print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


# 7. 2D Array

In [10]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)

[[10 20 30]
 [40 50 60]]


In [11]:
print(arr[0][0])
print(arr[1, 2])

10
60


# 8. Shape

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.shape)

(2, 3)


### shape batata hai array mein kitni rows aur columns hain.

2 rows
3 columns

# 9. ndim

In [13]:
arr1 = np.array([10, 20, 30])

print(arr1.ndim)

1


In [14]:
arr2 = np.array([
    [10, 20],
    [30, 40]
])

print(arr2.ndim)

2


### ndim batata hai array ki number of dimensions.

# 10. size

In [15]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.size)

6


### size batata hai total elements kitne hain.

# 11. dtype

In [16]:
arr = np.array([10, 20, 30, 40])

print(arr.dtype)

int64


### dtype batata hai array ke elements ka data type.

# 🔥 Ek saath sab properties

In [17]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


# 12. Basic Indexing and Slicing

## Already done above.

# 13. Practice Questions
Q1

NumPy import karke ye array banao:

[10, 20, 30, 40, 50]

Then print:

array

shape

ndim

size

dtype

In [22]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[10 20 30 40 50]
(5,)
1
5
int64


# Q2

## Ye 2D array banao:

1  2  3

4  5  6

7  8  9

## Print:

shape

ndim

size

In [25]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

(3, 3)
2
9


# Q3

## Q2 wale array se 5 access karo using indexing.

In [26]:
print(arr1[1,1])

5


# Q4

## Q2 wale array se 9 access karo.

In [27]:
print(arr1[2,2])

9


# Q5

## Q2 wale array ki second row print karo.

In [28]:
print(arr1[2])

[7 8 9]
